version: '2'
services:
  nestjs-app:
    build: .
    container_name: nestjs_app_container
    volumes:
      - ./src:/App/src:ro
    ports:
      - '5000:5000'
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    environment:
      - MYSQL_DATABASE=care
      - MYSQL_ROOT_PASSWORD=toor
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - db: /var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
# Names our volume
volumes:
  db:
    driver: local
